cmake_minimum_required(VERSION 3.0.2)
project(leo_guard)
find_package(catkin REQUIRED COMPONENTS rospy sensor_msgs std_msgs std_srvs geometry_msgs morai_msgs nav_msgs)
catkin_python_setup()
catkin_package()
catkin_install_python(PROGRAMS scripts/guard_node.py scripts/camera_lane_node.py scripts/signal_guard_node.py scripts/yield_observer_node.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
